// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvzwcfvpyfhqrykpqcwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2endjZnZweWZocXJ5a3BxY3dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTY4MTcsImV4cCI6MjA3MjA3MjgxN30.dEY-1z8sX7ussoQ4ZKlEGqzUtMqC5LmZ-2_H8g_vcco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});